### ISSUE TITLE
BSD/Linux differences in socket.h

### ISSUE THREAD

**Issue by john-tornblom** [OpenOrbis/musl#11]
The socket options for Linux and BSD use different values for, e.g., SO_REUSEADDR, which in turn cause setsockopt to behave incorrectly.

musl: #define SO_REUSEADDR    2
freebsd: #define SO_REUSEADDR    0x0004

**Comment by kiwidoggie** [comment]
Should be fixed in: https://github.com/OpenOrbis/musl/commit/091e9f0d5d9ab5a5535ddb9cfbb85ea665d5afcc
