### ISSUE TITLE
Sleep is broken

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/musl#4]
Originally reported by LM in the discord:

Apparently `sleep()` does not function properly, calling it is effectively a no-op.

**Comment by ChendoChap** [comment]
https://github.com/OpenOrbis/musl/blob/55b65f01d9c27a143474482a5678eccf938044c1/src/include/time.h#L7
nanosleep will end up calling this, this does not match freebsd's nanosleep syscall signature

**Comment by sleirsgoevy** [comment]
FreeBSD version matches the userspace nanosleep(const struct timespec*, struct timespec*), doesn't it?

By the way, why not just use the real libc?

**Comment by Cryptogenic** [comment]
> 
> 
> FreeBSD version matches the userspace nanosleep(const struct timespec*, struct timespec*), doesn't it?
> 
> By the way, why not just use the real libc?

The wrapper currently ifdef's out the implementation for ps4 because it uses syscalls that aren't present on FreeBSD 9 (such as sys_clock_nanosleep), I'll fix this today.

Regarding real libc, libc is loaded by applications from the package. We do not own the rights to redistribute PS4's libc, so we either have to use sceLibcInternal (not great, misses stuff that's important).

On top of that we need an open libc for portability. Anything that depends on libc (libc++ for example) needs to be able to build against it, so that's why we use musl.
